version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/Extensions/ArtifactDescription/ArtifactDescriptionTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/BuildUpdating/BuildRetensionTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/BuildUpdating/BuildVariableTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/BuildUpdating/GetBuildDefinitionVariableValueTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/FileUtilities/XmlFileUpdateTaskk" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/Versioning/VersionAndroidManifest" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/Versioning/VersionAngularFileTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/Versioning/VersionDotNetCoreAssembliesTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/Versioning/VersionIOSPlistManifest" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/Versioning/VersionJSONFileTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/WikiPDFExport/WikiPDFExportTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/WikiUpdater/WikiFolderUpdaterTask" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/Extensions/WikiUpdater/WikiUpdaterTask" 
    schedule:
      interval: "weekly"
 - package-ecosystem: "npm" 
    directory: "/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask" 
    schedule:
      interval: "weekly"
 - package-ecosystem: "npm" 
    directory: "/Extensions/YamlGenerator/YamlGeneratorTask" 
    schedule:
      interval: "weekly"
 - package-ecosystem: "npm" 
    directory: "/Extensions/Tools/GetAPIJsonPayloads" 
    schedule:
      interval: "weekly"
