name: Feature request
description:  Suggest an idea for this project
labels: [enhancement]
body:
- type: dropdown
  id: extension
  attributes:
    label: Azure DevOps Extensions
    description: "There are a number of Azure DevOps extensions in this repo so please state which one the bug relates to"
    options:
      - Artifact PR Description
      - Built Utilities
      - DevTest Labs
      - File Copier
      - Generate Release Notes (Node Cross Platform)
      - Manifest Versioning
      - WIKI Updater
      - WIKI PDF Generator
      - YAML Generator
      - Other
  validations:
    required: true
- type: textarea
  id: request
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is.
    placeholder: Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  id: solution
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  id: alternates
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  id: extra
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false

